language: node_js
dist: trusty
node_js:
  - "4"
  - "6"
  - "7"
  - "8"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
env:
  - CXX=g++-4.9
sudo: false
